# Generated by Django 5.1.6 on 2025-03-26 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_app', '0002_splitmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitmodel',
            name='expanse',
        ),
        migrations.AddField(
            model_name='splitmodel',
            name='expense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='split_expenses', to='Expense_app.expensemodels'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='splitmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
