# Generated by Django 5.1.6 on 2025-03-27 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_app', '0003_remove_splitmodel_expanse_splitmodel_expense_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_data', models.DateField(auto_now_add=True)),
                ('pay_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_payer', to=settings.AUTH_USER_MODEL)),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
