# Generated by Django 5.1.6 on 2025-03-28 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense_app', '0004_settlement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settlement',
            old_name='paid_data',
            new_name='paid_date',
        ),
    ]
